### ISSUE TITLE
Cant bring html element to zero

### ISSUE THREAD

**Issue by MarkusHeinisch** [alexfoxy/laxxx#152]
Hello sir, can you give me some help? I can't bring the second foo-div to zero. If i remove the first foo-div, it works. But i need two the two divs.

[https://xw9qt.csb.app/](url)

**Comment by alexfoxy** [comment]
Hi Markus can you provide a code example?

**Comment by MarkusHeinisch** [comment]
Yes. Show at the codebox-Link ;-)

[https://xw9qt.csb.app/](url)

You have copy&paste into your browser, github cant link it directly to codesandbox atm, sorry.

**Comment by rickvian** [comment]
what do you mean by zero?
is the height zero? or z-index zero?

the codebox link is broken from my side

**Comment by MarkusHeinisch** [comment]
With zero i mean left: 0. Please copy the link and paste it into your browser. Githubs comment-interface breaks the link.

**Comment by alexfoxy** [comment]
Can you provide a code example - otherwise I can't help :)

**Comment by MarkusHeinisch** [comment]
I have added a link in my first and da second post Alex.

**Comment by arthurdenner** [comment]
@MarkusHeinisch, I guess they were confused because your link wasn't formatted for Markdown.
You need to write it like `[https://xw9qt.csb.app/](https://xw9qt.csb.app/)` to it can link to [https://xw9qt.csb.app/](https://xw9qt.csb.app/) properly.

Just to save other's time, here's the source code of the sandbox - [https://codesandbox.io/s/xw9qt](https://codesandbox.io/s/xw9qt).

**Comment by alexfoxy** [comment]
Thanks @arthurdenner.

@MarkusHeinisch as you are using the selector `lax.addElements('.lax-slideX-ltr-text', ...` you need to make sure both divs have this class:
<img width="432" alt="Screenshot 2021-07-07 at 08 05 19" src="https://user-images.githubusercontent.com/151772/124714766-162a6700-defa-11eb-9a05-f98ba8ae7022.png">

I added this and now it works :)
